# Generated by Django 5.2.5 on 2025-09-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='images/default_user_photo.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
